### ISSUE TITLE
Precinct names in NJ need to have their names standardized

### ISSUE THREAD

**Issue by arashmahdian** [MEDSL/replication-scripts#4]
There are at least 414 precincts that the names have additional identifier (city, township, borough, ...) for the presidential votes, but not for the house votes. Examples below:

presidential votes      house votes

ABSECON CITY   vs ABSECON 
ALEXANDRIA TWP ALEXANDRIA
ALLAMUCHY TWP. vs ALLAMUCHY
ALLENDALE BORO vs ALLENDALE

**Comment by sbaltzmit** [comment]
Hi @arashmahdian , sorry I didn't see these issue reports. I wasn't Watching this repository because it isn't associated with any dataset. Can you please submit any issue reports to the dataverse repository associated with the most recent version of a given dataset? You can find the dataverse here https://dataverse.harvard.edu/dataverse/medsl. Thanks

**Comment by arashmahdian** [comment]
@sbaltzmit Thanks for taking care of these. I don't see any way of submitting issues on https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX for example. I assume I should sign up first? Also, I take it you mean for any future issues as you have fixed these four already?
